packages:
  - playground

allowBuilds:
  core-js: false
minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rsbuild/core'
  - '@rsbuild/plugin-*'
  - '@rslib/*'
  - '@rslint/*'
  - '@rspack/*'
  - '@rspress/*'
  - '@rstackjs/*'
  - '@rstest/*'
  - '@typescript/*'
  - 'rsbuild-plugin-*'
  - rstack
  - typescript
