allowBuilds:
  core-js: false
  simple-git-hooks: false
minimumReleaseAgeExclude:
  - '@rsbuild/core'
  - '@rsbuild/plugin-*'
  - typescript
  - '@typescript/*'
  - '@rstest/*'
  - '@rstackjs/test-utils@0.2.0'
